name: Build Electron App

on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: write  # needed for release action

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Build Windows x64 app
        run: npm run make:x64

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: out/make/   # <-- Changed this to the root out/make folder

  build-macos-x64:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Build macOS x64 app
        run: npm run make:x64

      - name: Upload macOS x64 build artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-x64-build
          path: "out/make/zip/darwin/x64/Kawaiii Timer-darwin-x64-1.0.0.zip"

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Build macOS arm64 app
        run: npm run make:arm64

      - name: Upload macOS arm64 build artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-build
          path: "out/make/zip/darwin/arm64/Kawaiii Timer-darwin-arm64-1.0.0.zip"

  release:
    needs: [build-windows, build-macos-x64, build-macos-arm64]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download Windows build artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: ./build/windows

      - name: Download macOS x64 build artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-x64-build
          path: ./build/macos/x64

      - name: Download macOS arm64 build artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-arm64-build
          path: ./build/macos/arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            ./build/windows/**/*.exe
            ./build/macos/x64/**/*.zip
            ./build/macos/arm64/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
